add check inputs

diff --git a/.github/workflows/createFB.yml b/.github/workflows/createFB.yml
--- a/.github/workflows/createFB.yml
+++ b/.github/workflows/createFB.yml
@@ -22,10 +22,24 @@ jobs:
     runs-on: ubuntu-latest
     timeout-minutes: 30
     steps:
+       - name: check inputs
+         run: | 
+          if [[ ! ${{inputs.ORIGIN_BRANCH}} =~ '' ]]; then
+            echo "Error: This field could not be empty"
+            exit 1
+          fi
+          if [[ ! ${{inputs.BRANCH}} =~ '' ]]; then
+            echo "Error: This field could not be empty"
+            exit 1
+          fi 
+          if [[ ! ${{inputs.ISSUE}} =~ '' ]]; then
+            echo "Error: This field could not be empty"
+            exit 1
+          fi  
        - name: Checkout
          uses: actions/checkout@v3
          with: 
-           ref: habib
+           ref: ready
            token: ${{ secrets.SWF_TOKEN }}
        - name: install ssh
          uses: shimataro/ssh-key-action@v2
